SELECT
       LCTO,
       Empresa,
       Item,
       Data,
       SUM(Pacotes) AS Pacotes,
       SUM(Toneladas) AS Toneladas,
       G_TOTAL_GERAL
       FROM (
        SELECT DISTINCT
               TMOV_ESTQ.LCTO,
               TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL EMPRESA,
               TITENS.COD_ITEM || ' - ' || TITENS.DESC_TECNICA ITEM,
               TMOV_ESTQ.DT DATA,
               TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1) Pacotes,
               ((TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) * (TITENS_ENGENHARIA.PESO_LIQ)) /1000 Toneladas,
               NULL AS G_TOTAL_GERAL
          FROM TITENS_ENGENHARIA TITENS_ENGENHARIA,
               TITENS_ENGENHARIA TITENS_ENGENHARIA1,
               TITENS_ESTOQUE TITENS_ESTOQUE,
               TTP_MOV_ESTQ TTP_MOV_ESTQ,
               TMOV_ESTQ TMOV_ESTQ,
               TITENS_COMERCIAL TITENS_COMERCIAL,
               TITENS_EMPR TITENS_EMPR,
               TITENS TITENS,
               TCUSTO_ESTQ TCUSTO_ESTQ,
               TEMPRESAS TEMPRESAS,
               TITENS_EMPR TITENS_EMPR1,
               TITENS TITENS1,
               TCAD_EST_ITE TCAD_EST_ITE,
               TGRP_CLAS_ITE TGRP_CLAS_ITE
        --  WHERE TITENS_EMPR.ID = TITENS_ENGENHARIA.ITEMPR_ID
        --    AND TITENS_EMPR1.ID = TITENS_ENGENHARIA1.ITEMPR_ID
        --    AND TGRP_CLAS_ITE.ID = TITENS_ENGENHARIA1.GRP_CLAS_ID
        --    AND TITENS_EMPR.ID = TITENS_ESTOQUE.ITEMPR_ID
        --    AND TTP_MOV_ESTQ.ID = TMOV_ESTQ.TMVES_ID
        --    AND TITENS_ESTOQUE.ID = TMOV_ESTQ.ITESTQ_ID
        --    AND TITENS_EMPR.ID = TITENS_COMERCIAL.ITEMPR_ID
          --  AND TEMPRESAS.ID = TITENS_EMPR.EMPR_ID
          --  AND TITENS.ID = TITENS_EMPR.ITEM_ID
        --    AND TMOV_ESTQ.ID = TCUSTO_ESTQ.MOV_ESTQ_ID
        --    AND TEMPRESAS.ID = TITENS_EMPR1.EMPR_ID
        --    AND TITENS1.ID = TITENS_EMPR1.ITEM_ID
          --  AND TITENS.ID(+) = TCAD_EST_ITE.FILHO_ID
        --    AND TITENS1.ID(+) = TCAD_EST_ITE.PAI_ID
        --    AND (TITENS_ENGENHARIA1.TP_ESTRUTURA = 'C')
        --    AND ((TTP_MOV_ESTQ.SIGLA in ('EPP','PPE')))
        --    AND (TCAD_EST_ITE.SEQ_ORD = 10)
        --    AND (TMOV_ESTQ.DT between TO_DATE ('01092024','DD/MM/RRRR') AND TO_DATE ('30092024','DD/MM/RRRR'))
        --    AND TITENS.COD_ITEM IN ('5004','5003')
          )
          GROUP BY 
               LCTO,
               Empresa,
               Item,
               Data,
               G_TOTAL_GERAL



###########################################################               
SELECT
       LCTO,
       Empresa,
       Item,
       Data,
       SUM(Pacotes) AS Pacotes,
       SUM(Toneladas) AS Toneladas,
       G_TOTAL_GERAL
       FROM (
        SELECT DISTINCT
               TMOV_ESTQ.LCTO,
               TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL EMPRESA,
               TITENS.COD_ITEM|| ' - ' || TITENS.DESC_TECNICA ITEM,
               TMOV_ESTQ.DT DATA,
               --SUM(TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) Pacotes,
               TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1) Pacotes,
               --SUM(((TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) * (TITENS_ENGENHARIA.PESO_LIQ))/1000) Toneladas,
               ((TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) * (TITENS_ENGENHARIA.PESO_LIQ)) /1000 Toneladas,
               NULL AS G_TOTAL_GERAL
          FROM TITENS_ENGENHARIA TITENS_ENGENHARIA,
               TITENS_ENGENHARIA TITENS_ENGENHARIA1,
               TITENS_ESTOQUE TITENS_ESTOQUE,
               TTP_MOV_ESTQ TTP_MOV_ESTQ,
               TMOV_ESTQ TMOV_ESTQ,
               TITENS_COMERCIAL TITENS_COMERCIAL,
               TITENS_EMPR TITENS_EMPR,
               TITENS TITENS,
               TCUSTO_ESTQ TCUSTO_ESTQ,
               TEMPRESAS TEMPRESAS,
               TITENS_EMPR TITENS_EMPR1,
               TITENS TITENS1,
               TCAD_EST_ITE TCAD_EST_ITE,
               TGRP_CLAS_ITE TGRP_CLAS_ITE
         WHERE TITENS_EMPR.ID = TITENS_ENGENHARIA.ITEMPR_ID
           AND TITENS_EMPR1.ID = TITENS_ENGENHARIA1.ITEMPR_ID
           AND TGRP_CLAS_ITE.ID = TITENS_ENGENHARIA1.GRP_CLAS_ID
           AND TITENS_EMPR.ID = TITENS_ESTOQUE.ITEMPR_ID
           AND TTP_MOV_ESTQ.ID = TMOV_ESTQ.TMVES_ID
           AND TITENS_ESTOQUE.ID = TMOV_ESTQ.ITESTQ_ID
           AND TITENS_EMPR.ID = TITENS_COMERCIAL.ITEMPR_ID
           AND TEMPRESAS.ID = TITENS_EMPR.EMPR_ID
           AND TITENS.ID = TITENS_EMPR.ITEM_ID
           AND TMOV_ESTQ.ID = TCUSTO_ESTQ.MOV_ESTQ_ID
           AND TEMPRESAS.ID = TITENS_EMPR1.EMPR_ID
           AND TITENS1.ID = TITENS_EMPR1.ITEM_ID
           AND TITENS.ID(+) = TCAD_EST_ITE.FILHO_ID
           AND TITENS1.ID(+) = TCAD_EST_ITE.PAI_ID
           AND (TITENS_ENGENHARIA1.TP_ESTRUTURA = 'C')
           AND ((TTP_MOV_ESTQ.SIGLA in ('EPP','PPE')))
           AND (TCAD_EST_ITE.SEQ_ORD = 10)
           --AND (TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL = '1 - Irm達os Ruivo Ltda')
           AND (TMOV_ESTQ.DT between TO_DATE ('01092024','DD/MM/RRRR') AND TO_DATE ('30092024','DD/MM/RRRR'))
          )
          GROUP BY 
               LCTO,
               Empresa,
               Item,
               Data,
               G_TOTAL_GERAL








SELECT TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL Empresa,
       TITENS1.COD_ITEM || ' - ' || TITENS1.DESC_TECNICA Item,
       TMOV_ESTQ.DT Data,
       SUM(TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) Pacotes,
       SUM(((TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) * (TITENS_ENGENHARIA.PESO_LIQ))/1000) Toneladas,
       NULL G_TOTAL_GERAL
  FROM TITENS_ENGENHARIA TITENS_ENGENHARIA,
       TITENS_ENGENHARIA TITENS_ENGENHARIA1,
       TITENS_ESTOQUE TITENS_ESTOQUE,
       TTP_MOV_ESTQ TTP_MOV_ESTQ,
       TMOV_ESTQ TMOV_ESTQ,
       TITENS_COMERCIAL TITENS_COMERCIAL,
       TITENS_EMPR TITENS_EMPR,
       TITENS TITENS,
       TCUSTO_ESTQ TCUSTO_ESTQ,
       TEMPRESAS TEMPRESAS,
       TITENS_EMPR TITENS_EMPR1,
       TITENS TITENS1,
       TCAD_EST_ITE TCAD_EST_ITE,
       TGRP_CLAS_ITE TGRP_CLAS_ITE
 WHERE TITENS_EMPR.ID = TITENS_ENGENHARIA.ITEMPR_ID
   AND TITENS_EMPR1.ID = TITENS_ENGENHARIA1.ITEMPR_ID
   AND TGRP_CLAS_ITE.ID = TITENS_ENGENHARIA1.GRP_CLAS_ID
   AND TITENS_EMPR.ID = TITENS_ESTOQUE.ITEMPR_ID
   AND TTP_MOV_ESTQ.ID = TMOV_ESTQ.TMVES_ID
   AND TITENS_ESTOQUE.ID = TMOV_ESTQ.ITESTQ_ID
   AND TITENS_EMPR.ID = TITENS_COMERCIAL.ITEMPR_ID
   AND TEMPRESAS.ID = TITENS_EMPR.EMPR_ID
   AND TITENS.ID = TITENS_EMPR.ITEM_ID
   AND TMOV_ESTQ.ID = TCUSTO_ESTQ.MOV_ESTQ_ID
   AND TEMPRESAS.ID = TITENS_EMPR1.EMPR_ID
   AND TITENS1.ID = TITENS_EMPR1.ITEM_ID
   AND TITENS.ID(+) = TCAD_EST_ITE.FILHO_ID
   AND TITENS1.ID(+) = TCAD_EST_ITE.PAI_ID
   AND (TITENS_ENGENHARIA1.TP_ESTRUTURA = 'C')
   AND (( TTP_MOV_ESTQ.SIGLA in ('EPP','PPE')))
   AND (TCAD_EST_ITE.SEQ_ORD = 10)
   AND (TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL = '1 - Irmãos Ruivo Ltda')
   AND ( TMOV_ESTQ.DT between TO_DATE ('01082024','DD/MM/RRRR') AND TO_DATE ('31082024','DD/MM/RRRR'))
GROUP BY TITENS.COD_ITEM,
         TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL,
         TITENS1.COD_ITEM || ' - ' || TITENS1.DESC_TECNICA,
         TMOV_ESTQ.DT
ORDER BY TITENS1.COD_ITEM || ' - ' || TITENS1.DESC_TECNICA ASC















SELECT TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL Empresa,
       TITENS1.COD_ITEM || ' - ' || TITENS1.DESC_TECNICA Item,
       TMOV_ESTQ.DT Data,
       SUM(TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) Pacotes,
       SUM(((TMOV_ESTQ.QTDE * decode(TMOV_ESTQ.ENT_SAI,'S',-1,1)) * (TITENS_ENGENHARIA.PESO_LIQ))/1000) Toneladas,
       NULL G_TOTAL_GERAL
  FROM TITENS_ENGENHARIA TITENS_ENGENHARIA,
       TITENS_ENGENHARIA TITENS_ENGENHARIA1,
       TITENS_ESTOQUE TITENS_ESTOQUE,
       TTP_MOV_ESTQ TTP_MOV_ESTQ,
       TMOV_ESTQ TMOV_ESTQ,
       TITENS_COMERCIAL TITENS_COMERCIAL,
       TITENS_EMPR TITENS_EMPR,
       TITENS TITENS,
       TCUSTO_ESTQ TCUSTO_ESTQ,
       TEMPRESAS TEMPRESAS,
       TITENS_EMPR TITENS_EMPR1,
       TITENS TITENS1,
       TCAD_EST_ITE TCAD_EST_ITE,
       TGRP_CLAS_ITE TGRP_CLAS_ITE
 WHERE TITENS_EMPR.ID = TITENS_ENGENHARIA.ITEMPR_ID
   AND TGRP_CLAS_ITE.ID = TITENS_ENGENHARIA1.GRP_CLAS_ID
   AND TITENS_EMPR1.ID = TITENS_ENGENHARIA1.ITEMPR_ID
   AND TITENS_EMPR.ID = TITENS_ESTOQUE.ITEMPR_ID
   AND TITENS_ESTOQUE.ID = TMOV_ESTQ.ITESTQ_ID
   AND TTP_MOV_ESTQ.ID = TMOV_ESTQ.TMVES_ID
   AND TITENS_EMPR.ID = TITENS_COMERCIAL.ITEMPR_ID
   AND TITENS.ID = TITENS_EMPR.ITEM_ID
   AND TEMPRESAS.ID = TITENS_EMPR.EMPR_ID
   AND TMOV_ESTQ.ID = TCUSTO_ESTQ.MOV_ESTQ_ID
   AND TITENS1.ID = TITENS_EMPR1.ITEM_ID
   AND TEMPRESAS.ID = TITENS_EMPR1.EMPR_ID
   AND TITENS1.ID(+) = TCAD_EST_ITE.PAI_ID
   AND TITENS.ID(+) = TCAD_EST_ITE.FILHO_ID
   AND (TITENS_ENGENHARIA1.TP_ESTRUTURA = 'C')
   AND (( TTP_MOV_ESTQ.SIGLA in ('EPP','PPE')))
   AND (TCAD_EST_ITE.SEQ_ORD = 10)
   AND (TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL = '1 - Irmãos Ruivo Ltda')
   AND ( TMOV_ESTQ.DT between TO_DATE ('01082024','DD/MM/RRRR') AND TO_DATE ('31082024','DD/MM/RRRR'))
GROUP BY TITENS.COD_ITEM,
         TEMPRESAS.COD_EMP ||  ' - ' || TEMPRESAS.RAZAO_SOCIAL,
         TITENS1.COD_ITEM || ' - ' || TITENS1.DESC_TECNICA,
         TMOV_ESTQ.DT
ORDER BY TITENS1.COD_ITEM || ' - ' || TITENS1.DESC_TECNICA ASC