List de Cliente x Tab de Venda X Estab para importar EDI pedido - MV
-- Com filtro no código do cliente, empresa e CNPJ

-- SELECT EMPCLI.EMPR_ID
    --  , CLI.COD_CLI
    --  , CLI.DESCRICAO
    --  , EST.COD_EST
    --  , EST.NOME_FAN FANTASIA
    --  , EST.CNPJ
    --  , EST_C.COD_EST EST_COBRANCA
    --  , EST_E.COD_EST EST_ENTRADA
    --  , EST_F.COD_EST EST_FATURA
    --  , TPRVEN.COD_PREVEN COD_TAB_VENDA
    --  , TPRVEN.DESCRICAO TAB_VENDA
    --  , REP.COD_REP
    --  , REP.DESCRICAO REPRESENTANTE
--   FROM TCLIENTES         CLI
    --  , TESTABELECIMENTOS EST
    --  , TEST_EST_COBR     E_C
    --  , TESTABELECIMENTOS EST_C
    --  , TEST_EST_ENTR     E_E
    --  , TESTABELECIMENTOS EST_E
    --  , TESTABELECIMENTOS EST_F
    --  , TEMP_CLI          EMPCLI
    --  , TESTAB_DADOS_FAT  ESTFAT
    --  , TPRECOSVEN        TPRVEN
    --  , TEST_REP          EREP
    --  , TREPRESENTANTES   REP
--  WHERE CLI.ID          = EST.CLI_ID
--    AND EST.ID          = E_C.EST_ID
--    AND EST_C.ID        = E_C.EST_ID_COBR
--    AND EST.ID          = E_E.EST_ID 
--    AND EST_E.ID        = E_E.EST_ID_ENTR
--    AND EST_F.ID        = CLI.EST_ID_FAT
--    AND CLI.ID          = EMPCLI.CLI_ID
--    AND EST.ID          = ESTFAT.EST_ID
--    AND EMPCLI.ID       = ESTFAT.EMPCLI_ID
--    AND TPRVEN.ID(+)    = ESTFAT.TPRVEN_ID
--    AND EST.ID          = EREP.EST_ID
--    AND EMPCLI.ID       = EREP.EMPCLI_ID
--    AND REP.ID          = EREP.REP_ID
--  ORDER BY EMPCLI.EMPR_ID
        -- , CLI.COD_CLI
        -- , EST.COD_EST



SELECT TEMP_CLI.EMPR_ID             EMPR_ID,
       TCLIENTES.COD_CLI            COD_CLI,
       TCLIENTES.DESCRICAO          CLIENTE,
       TESTABELECIMENTOS.COD_EST    COD_EST,
       TESTABELECIMENTOS.NOME_FAN   NOME_FAN,
       TESTABELECIMENTOS.CNPJ       CNPJ,
       TESTABELECIMENTOS1.COD_EST   EST_COBRANCA,
       TESTABELECIMENTOS2.COD_EST   EST_ENTRADA,
       TESTABELECIMENTOS3.COD_EST   EST_FATURA,
       TPRECOSVEN.COD_PREVEN        COD_TAB_VENDA,
       TPRECOSVEN.DESCRICAO         TAB_VENDA,
       TREPRESENTANTES.COD_REP      COD_REP,
       TREPRESENTANTES.DESCRICAO    REPRESENTANTE
  FROM TCLIENTES            TCLIENTES,          -- Tabela de Clientes
       TPRECOSVEN           TPRECOSVEN,         -- Tabela Preço de Vendas
       TEST_REP             TEST_REP,
       TESTABELECIMENTOS    TESTABELECIMENTOS,
       TEST_EST_COBR        TEST_EST_COBR,
       TESTABELECIMENTOS    TESTABELECIMENTOS1,
       TESTABELECIMENTOS    TESTABELECIMENTOS2,
       TESTABELECIMENTOS    TESTABELECIMENTOS3,
       TEMP_CLI             TEMP_CLI,
       TESTAB_DADOS_FAT     TESTAB_DADOS_FAT,
       TREPRESENTANTES      TREPRESENTANTES,
       TEST_EST_ENTR        TEST_EST_ENTR
 WHERE TESTABELECIMENTOS3.ID    = TCLIENTES.EST_ID_FAT
   AND TESTABELECIMENTOS.ID     = TEST_REP.EST_ID
   AND TREPRESENTANTES.ID       = TEST_REP.REP_ID
   AND TEMP_CLI.ID              = TEST_REP.EMPCLI_ID
   AND TCLIENTES.ID             = TESTABELECIMENTOS.CLI_ID
   AND TESTABELECIMENTOS.ID     = TEST_EST_COBR.EST_ID
   AND TESTABELECIMENTOS1.ID    = TEST_EST_COBR.EST_ID_COBR
   AND TCLIENTES.ID             = TEMP_CLI.CLI_ID
   AND TESTABELECIMENTOS.ID     = TESTAB_DADOS_FAT.EST_ID
   AND TPRECOSVEN.ID(+)         = TESTAB_DADOS_FAT.TPRVEN_ID
   AND TEMP_CLI.ID              = TESTAB_DADOS_FAT.EMPCLI_ID
   AND TESTABELECIMENTOS.ID     = TEST_EST_ENTR.EST_ID
   AND TESTABELECIMENTOS2.ID    = TEST_EST_ENTR.EST_ID_ENTR
ORDER BY TEMP_CLI.EMPR_ID ASC, TCLIENTES.COD_CLI ASC, TESTABELECIMENTOS.COD_EST ASC
