-- **MLC012 RJ Valorização Ordens - Sintético**

TEMPRESAS.COD_EMP Empresa,
to_char(trunc(TVALORIZACOES_OFS.DATA),'MM/RRRR') Mês_Ano,
DECODE(TOPERACAO.ORIGEM, 'T', 'TERCEIROS', 'I', 'INTERNA') Origem_CC,
TCC.COD CC_Cód,
TCC.DESCRICAO CC_Descrição,
TORDENS.NUM_ORDEM NUM_ORDEM,
TCENTROS_TRAB.COD_CENTRO COD_CENTRO_t,
TOPERACAO.DESCRICAO DESCRICAO,
TVALORIZACOES_OFS.TEMPO_OPERACAO Tempo,
nvl(TVALORIZACOES_OFS.VLR_OPERACAO,0) Vlr_Operação,
TVALORIZACOES_OFS.TP_LCTO TP_Lcto,
TORDENS_MOVTO.DT_APONT DT_APONT
FROM TCENTROS_TRAB TCENTROS_TRAB,
TORDENS_ROT TORDENS_ROT,
TEMP_CC TEMP_CC,
TORDENS TORDENS,
TVALORIZACOES_OFS TVALORIZACOES_OFS,
TOPERACAO TOPERACAO,
TCC TCC,
TITENS_PLANEJAMENTO TITENS_PLANEJAMENTO,
TITENS_EMPR TITENS_EMPR,
TITENS TITENS,
TEMPRESAS TEMPRESAS,
TORDENS_MOVTO TORDENS_MOVTO
WHERE TCENTROS_TRAB.ID(+) = TORDENS_ROT.CENTR_TRAB_ID
AND TORDENS_ROT.ID(+) = TORDENS_MOVTO.TORDEN_ROT_IDz
AND TORDENS_ROT.ID = TVALORIZACOES_OFS.TORDEN_ROT_ID
AND TEMP_CC.ID(+) = TCENTROS_TRAB.EMP_CC_ID
AND [TORDENS.ID](http://tordens.id/) = TVALORIZACOES_OFS.ORDEM_ID
AND [TORDENS.ID](http://tordens.id/)(+) = TORDENS_ROT.ORDEM_ID
AND [TOPERACAO.ID](http://toperacao.id/) = TORDENS_ROT.OPERACAO_ID
AND [TCC.ID](http://tcc.id/)(+) = TEMP_CC.CC_ID
AND TITENS_PLANEJAMENTO.ID = TORDENS.ITPL_ID
AND TITENS_EMPR.ID = TITENS_PLANEJAMENTO.ITEMPR_ID(+)
AND [TITENS.ID](http://titens.id/) = TITENS_EMPR.ITEM_ID
AND [TEMPRESAS.ID](http://tempresas.id/) = TITENS_EMPR.EMPR_ID
AND (TEMPRESAS.COD_EMP = 1)
AND (to_char(trunc(TVALORIZACOES_OFS.DATA),'MM/RRRR') = '09/2024')
AND (TOPERACAO.ORIGEM = 'I')
AND (TCC.COD = 1001001)
AND ( TORDENS_MOVTO.DT_APONT between TO_DATE ('01/09/2024','DD/MM/RRRR') 
AND TO_DATE ('30/09/2024','DD/MM/RRRR'))
ORDER BY TEMPRESAS.COD_EMP ASC,
to_char(trunc(TVALORIZACOES_OFS.DATA),'MM/RRRR') ASC,
TCC.COD ASC,
TVALORIZACOES_OFS.TP_LCTO ASC








-- **RELATORIO DE CUSTOS OPERACIONAIS - MV**

SELECT TORDENS.NUM_ORDEM Numero_da_Ordem,
TORDENS.DT_EMISSAO Data,
TORDENS.QTDE_ENTREGUE Qtde_Entregue,
TCC.COD Cod_Centro_Custo,
TCC.DESCRICAO Desc_Centro_Custo,
TCENTROS_TRAB.COD_CENTRO Cod_Centro_Trabalho,
TCENTROS_TRAB.DESCRICAO Desc_Centro_Trabalho,
TOPERACAO.COD_OPERACAO Cod_Centro_Operacao,
TOPERACAO.DESCRICAO Desc_Centro_Operacao,
TUNID_MED.DESCRICAO Unid_Medida,
NVL(TORDENS_ROT.TEMPO, 0) * TORDENS.QTDE_ENTREGUE Tempo,
NULL G_TOTAL_GERAL
FROM TITENS_PLANEJAMENTO TITENS_PLANEJAMENTO,
TITENS_EMPR TITENS_EMPR,
TEMPRESAS TEMPRESAS,
TITENS TITENS,
TORDENS_ROT TORDENS_ROT,
TCENTROS_TRAB TCENTROS_TRAB,
TORDENS TORDENS,
TOPERACAO TOPERACAO,
TUNID_MED TUNID_MED,
TEMP_CC TEMP_CC,
TCC TCC
WHERE TITENS_PLANEJAMENTO.ID = TORDENS.ITPL_ID
AND TITENS_EMPR.ID = TITENS_PLANEJAMENTO.ITEMPR_ID
AND [TEMPRESAS.ID](http://tempresas.id/) = TCENTROS_TRAB.EMPR_ID
AND [TEMPRESAS.ID](http://tempresas.id/) = TITENS_EMPR.EMPR_ID
AND [TITENS.ID](http://titens.id/) = TITENS_EMPR.ITEM_ID
AND TCENTROS_TRAB.ID = TORDENS_ROT.CENTR_TRAB_ID
AND [TORDENS.ID](http://tordens.id/) = TORDENS_ROT.ORDEM_ID
AND [TOPERACAO.ID](http://toperacao.id/) = TORDENS_ROT.OPERACAO_ID
AND TUNID_MED.ID = TORDENS_ROT.UNID_MED_ID
AND TEMP_CC.ID = TCENTROS_TRAB.EMP_CC_ID
AND [TCC.ID](http://tcc.id/) = TEMP_CC.CC_ID
AND TEMPRESAS.COD_EMP = 1
AND ( TORDENS.DT_EMISSAO between TO_DATE ('01/09/2024','DD/MM/RRRR') 
AND TO_DATE ('30/09/2024','DD/MM/RRRR'))
AND (TCC.COD = 1001001)
AND TORDENS_ROT.TEMPO > 0