SELECT DISTINCT TREL_DEM.CODIGO Relatorio,
       TCTA_CTAB.COD_RED Conta_Reduzida,
       TCTA_CTAB.CTA Conta,
       TCTA_CTAB.DESCRICAO Desc_Da_Conta,
       TCC.COD Cod_CC,
       TCC.DESCRICAO Desc_CC,
       TFUNCIONARIOS.COD_FUNC Cod_Responsavel,
       TFUNCIONARIOS.NOME Nome_Responsavel,
       TVAL_DEM_CC.DATA Data,
       TVAL_DEM_CC.VALOR Valor
  FROM TEMPRESAS TEMPRESAS,
       TITENS_EMPR TITENS_EMPR,
       TREL_DEM TREL_DEM,
       TITENS_REL_DEM TITENS_REL_DEM,
       TITENS_REL_DEM_CC TITENS_REL_DEM_CC,
       TEMP_CC TEMP_CC,
       TCC TCC,
       TEMP_CTA_CTAB TEMP_CTA_CTAB,
       TCTA_CTAB TCTA_CTAB,
       TVAL_DEM_CC TVAL_DEM_CC,
       TFUNCIONARIOS TFUNCIONARIOS
 WHERE TEMPRESAS.ID = TITENS_EMPR.EMPR_ID
   AND TREL_DEM.ID = TITENS_REL_DEM.TREL_DEM_ID
   AND TITENS_REL_DEM.ID = TITENS_REL_DEM_CC.TITENS_REL_ID
   AND TITENS_REL_DEM_CC.ID = TVAL_DEM_CC.TITENS_REL_CC_ID
   AND TEMP_CC.ID = TITENS_REL_DEM_CC.EMP_CC_ID
   AND TCC.ID = TEMP_CC.CC_ID
   AND TEMP_CTA_CTAB.ID = TITENS_REL_DEM_CC.EMP_CTA_ID
   AND TCTA_CTAB.ID = TEMP_CTA_CTAB.CTA_CTAB_ID
   AND TFUNCIONARIOS.ID = TITENS_REL_DEM_CC.FUNC_ID
   AND TEMPRESAS.COD_EMP = 1
   AND ( TVAL_DEM_CC.DATA between TO_DATE ('01/01/2024','DD/MM/RRRR') AND TO_DATE ('30/01/2024','DD/MM/RRRR'))