SELECT TEMPRESAS.COD_EMP || ' - ' || TEMPRESAS.RAZAO_SOCIAL EMPRESA,
       TCLIENTES.COD_CLI || ' - ' || TCLIENTES.DESCRICAO CLIENTE,
       TPEDIDOS_VENDA.NUM_PEDIDO PEDIDO,
       TPEDIDOS_VENDA.DT_EMIS DATA_EMISSAO,
       TPEDIDOS_VENDA.DT_ENTREGA DATA_ENTREGA,
       TPEDIDOS_VENDA.POS_PDV POSICAO_PDV,
       TDIVISOES_VENDAS.COD_DIVD DIVISAO_DE_VENDA,
       TPEDIDOS_VENDA.TIPO TIPO,
       TPEDIDOS_VENDA.OBS OBS,
       TITENS_PDV.NUM_ITEM NUM_ITEM,
       TDIVISOES_VENDAS.DESCRICAO DESCRICAO,
       TPEDIDOS_VENDA.NUM_PEDIDO NUM_PEDIDO,
       TNFS_SAIDA.NUM_NF NUM_NF,
       TTIPOS_NF.DESCRICAO_NF DESCRICAO_NF
  FROM THIST_MOV_ITE_PDV THIST_MOV_ITE_PDV,
       TITENS_NFS TITENS_NFS,
       TITENS_PDV TITENS_PDV,
       TDIVISOES_VENDAS TDIVISOES_VENDAS,
       TPEDIDOS_VENDA TPEDIDOS_VENDA,
       TNFS_SAIDA TNFS_SAIDA,
       TTIPOS_NF TTIPOS_NF,
       TCLIENTES TCLIENTES,
       TEMPRESAS TEMPRESAS
 WHERE TITENS_NFS.ID                = THIST_MOV_ITE_PDV.ITNFS_ID
   AND TITENS_PDV.ID                = THIST_MOV_ITE_PDV.ITPDV_ID
   AND TDIVISOES_VENDAS.ID          = TITENS_NFS.DIVD_ID
   AND TNFS_SAIDA.ID                = TITENS_NFS.NFS_ID
   AND TTIPOS_NF.ID                 = TITENS_NFS.TPNF_ID
   AND TDIVISOES_VENDAS.ID          = TITENS_PDV.DIVD_ID
   AND TPEDIDOS_VENDA.ID            = TITENS_PDV.PDV_ID
   AND (TDIVISOES_VENDAS.COD_DIVD   = 99)
   AND (TNFS_SAIDA.SIT_NF           = 'I')
ORDER BY TITENS_PDV.NUM_ITEM ASC